version: '3.7'

services:
    go-rest-api:
        container_name: go-rest-api
        image: go-rest-api:dev
        build: ./
        ports:
            - "8080:8080"
        depends_on: 
            - postgres
    postgres:
        container_name: postgres-go
        image: postgres
        ports: 
            - "5432:5432"
        volumes: 
            - ./init_db:/docker-entrypoint-initdb.d/
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=go_db
      